### ISSUE TITLE
shanghaitech训练问题

### ISSUE THREAD

**Issue by XinyiWang1123** [Myzhao1999/LGN-Net#4]
请问为什么我在训练shanghaitech数据集时，运行一会报错Traceback (most recent call last):
  File "Train.py", line 130, in <module>
    main()
  File "Train.py", line 104, in main
    for j, (imgs) in enumerate(train_batch):
  File "/home/ubuntu/anaconda3/envs/uvad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/ubuntu/anaconda3/envs/uvad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/ubuntu/anaconda3/envs/uvad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/ubuntu/anaconda3/envs/uvad/lib/python3.8/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/uvad/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ubuntu/anaconda3/envs/uvad/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ubuntu/anaconda3/envs/uvad/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ubuntu/wxy/LGN-Net/model/utils.py", line 77, in __getitem__
    image = np_load_frame(self.videos[video_name]['frame'][frame_name+i], self._resize_height, self._resize_width)
IndexError: list index out of range数据是按照330个视频下，每个视频下包含帧的格式存储的。

**Comment by Sweiying** [comment]
I would like to ask if you have solved this problem, I still have not been successful

**Comment by yinyexingchen** [comment]
> 请问为什么我在训练shanghaitech数据集时，运行一会报错Traceback (most recent call last): File "Train.py", line 130, in main() File "Train.py", line 104, in main for j, (imgs) in enumerate(train_batch): File "/home/ubuntu/anaconda3/envs/uvad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in **next** data = self._next_data() File "/home/ubuntu/anaconda3/envs/uvad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data return self._process_data(data) File "/home/ubuntu/anaconda3/envs/uvad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data data.reraise() File "/home/ubuntu/anaconda3/envs/uvad/lib/python3.8/site-packages/torch/_utils.py", line 425, in reraise raise self.exc_type(msg) IndexError: Caught IndexError in DataLoader worker process 0. Original Traceback (most recent call last): File "/home/ubuntu/anaconda3/envs/uvad/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop data = fetcher.fetch(index) File "/home/ubuntu/anaconda3/envs/uvad/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "/home/ubuntu/anaconda3/envs/uvad/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in data = [self.dataset[idx] for idx in possibly_batched_index] File "/home/ubuntu/wxy/LGN-Net/model/utils.py", line 77, in **getitem** image = np_load_frame(self.videos[video_name]['frame'][frame_name+i], self._resize_height, self._resize_width) IndexError: list index out of range数据是按照330个视频下，每个视频下包含帧的格式存储的。

你好，请问你解决这个问题了吗，你是对视频的每帧都进行抽取吗

**Comment by yinyexingchen** [comment]
> I would like to ask if you have solved this problem, I still have not been successful

hello，have you solve this problem？thx in advance
